### ISSUE TITLE
Empty results with Darwin Unified Log extension

### ISSUE THREAD

**Issue by mike-myers-tob** [trailofbits/osquery-extensions#67]
User reports that he builds and loads the Darwin Unified Log extension, but querying it returns an empty table.

Confirmed locally, there's a logic bug preventing it from working. More details TBA.

**Comment by GarretReece** [comment]
It looks like the update back in March introduced a logic error, where now at line [197](https://github.com/trailofbits/osquery-extensions/blob/40269a7f5d6c72eba0c6c6976963899e1477ccc5/darwin_unified_log/src/system_log.cpp#L197) of `system_log.cpp` the code copies from `entries` to `entries`, rather than copying from `new_entries` to `entries`. Hopefully it's not that tricky a fix.

**Comment by mike-myers-tob** [comment]
See #71

**Comment by LeShadow** [comment]
@mike-myers-tob I am the person who originally reported this issue on slack ^^.

How is this bug related to #71 which is about the mdm enrollment functionality? did you mean #72 ?

**Comment by mike-myers-tob** [comment]
I did, sorry for the mistake
